USE planme_schema;

DROP TABLE IF EXISTS Tasks;

CREATE TABLE Tasks (
	ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    TaskBoard INT UNSIGNED,
    TaskName VARCHAR(20) NOT NULL,
    EffortValue INT,
    Description VARCHAR(500),
    State INT UNSIGNED DEFAULT 1,
    FOREIGN KEY(State) REFERENCES TaskStates(ID) ON DELETE CASCADE,
    FOREIGN KEY(TaskBoard) REFERENCES TaskBoards(ID) ON DELETE CASCADE
);