USE planme_schema;

#DROP TABLE IF EXISTS ProjectMemberships;

CREATE TABLE ProjectMemberships (
	ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    UserID INT UNSIGNED NOT NULL,
    ProjectID INT UNSIGNED NOT NULL,
    FOREIGN KEY(UserID) REFERENCES Users(ID) ON DELETE CASCADE,
    FOREIGN KEY(ProjectID) REFERENCES Projects(ID) ON DELETE CASCADE
);