USE planme_schema;

DROP TABLE IF EXISTS Projects;

CREATE TABLE Projects (
	ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    OwnerID INT UNSIGNED,
    ProjectName VARCHAR(30),
    FOREIGN KEY(OwnerID) REFERENCES Users(ID) ON DELETE CASCADE
);