USE planme_schema;

DROP TABLE IF EXISTS TaskAssignments;

CREATE TABLE TaskAssignments (
	ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    UserID INT UNSIGNED NOT NULL,
    TaskID INT UNSIGNED NOT NULL,
    FOREIGN KEY(UserID) REFERENCES Users(ID),
    FOREIGN KEY(TaskID) REFERENCES Tasks(ID)
);