USE planme_schema;

DROP TABLE IF EXISTS Threads;

CREATE TABLE Threads (
	ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Project INT UNSIGNED NOT NULL,
    Author INT UNSIGNED,
    Title VARCHAR(50),
    Content VARCHAR(1000),
    Posted TIMESTAMP,
    FOREIGN KEY(Project) REFERENCES Projects(ID) ON DELETE CASCADE,
    FOREIGN KEY(Author) REFERENCES Users(ID)
);